sudo: required
services:
  - docker

before_install:
  - docker build -t leonciodiego/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run leonciodiego/react-test npm test -- --coverage

after_success:
  - docker build -t leonciodiego/multi-client ./client
  - docker build -t leonciodiego/multi-nginx ./nginx
  - docker build -t leonciodiego/multi-server ./server
  - docker build -t leonciodiego/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push leonciodiego/multi-client
  - docker push leonciodiego/multi-nginx
  - docker push leonciodiego/multi-server
  - docker push leonciodiego/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: AWSAppWeb
  env: multi-docker
  bucket_name: elasticbeanstalk-us-west-2-336142811313
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret access key:
    secure: $AWS_SECRET_KEY
